source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'TMOTableView'
pod 'Canvas'
pod 'SimpleMotionEffects'
pod 'CSStickyHeaderFlowLayout'
pod 'AFNetworking', '~> 2.0'
pod 'ionicons'
pod 'DZNEmptyDataSet'
pod 'UIImageView-Letters'
pod 'APPaginalTableView'
pod 'VBFPopFlatButton'
pod 'SwipeView'
pod 'ChameleonFramework'
pod 'TOMSMorphingLabel', '~> 0.2.2'
pod 'OTMWebView'
pod 'Mixpanel'